# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /feedstock/recipe, last modified Wed Jan 18 19:38:33 2023
# ------------------------------------------------

package:
  name: xz
  version: 5.2.10
source:
  sha256: 01b71df61521d9da698ce3c33148bff06a131628ff037398c09482f3a26e5408
  url: https://sourceforge.net/projects/lzmautils/files/xz-5.2.10.tar.bz2
build:
  number: '1'
  run_exports:
    - xz >=5.2.10,<6.0a0
  string: h5eee18b_1
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - autoconf 2.71 pl5340h5eee18b_0
    - automake 1.16.5 pl5340h06a4308_1
    - binutils_impl_linux-64 2.38 h2a08ee3_1
    - binutils_linux-64 2.38.0 hc2dff05_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_0
    - gdbm 1.18 hd4cb3f1_4
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.38 h1181459_1
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libtool 2.4.6 h6a678d5_1009
    - m4 1.4.18 h4e445db_0
    - make 4.2.1 h1bed415_1
    - ncurses 6.3 h5eee18b_3
    - patch 2.7.6 h7b6447c_1001
    - perl 5.34.0 h5eee18b_2
    - readline 8.2 h5eee18b_0
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
  run:
    - libgcc-ng >=11.2.0
test:
  commands:
    - xz --help
    - unxz --help
    - lzma --help
    - conda inspect linkages -p $PREFIX $PKG_NAME
  requires:
    - conda-build
about:
  description: 'XZ Utils is free general-purpose data compression software with a
    high

    compression ratio. XZ Utils were written for POSIX-like systems, but also

    work on some not-so-POSIX systems.

    '
  dev_url: https://git.tukaani.org/
  doc_url: https://tukaani.org/xz/
  home: https://tukaani.org/xz/
  license: LGPL-2.1-or-later and GPL-2.0-or-later
  license_family: GPL2
  license_file: COPYING
  summary: Data compression software with high compression ratio
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: bd21efe9-6446-4787-98ac-1b6929566fe1
  recipe-maintainers:
    - mingwandroid
    - msarahan
    - nehaljwani
    - ocefpaf
    - scopatz
  remote_url: git@github.com:AnacondaRecipes/xz-feedstock.git
  sha: f55ff6dafd7dea69e59ab8993a950bf4572d480d
