# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /feedstock/recipe, last modified Mon Oct 24 21:46:53 2022
# ------------------------------------------------

package:
  name: readline
  version: '8.2'
source:
  sha256: 3feb7171f16a84ee82ca18a36d7b9be109a52c04f492a053331d7d1095007c35
  url: https://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz
build:
  number: '0'
  run_exports:
    - readline >=8.2,<9.0a0
  string: h5eee18b_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.38 h2a08ee3_1
    - binutils_linux-64 2.38.0 hc2dff05_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_0
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.38 h1181459_1
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - make 4.2.1 h1bed415_1
    - pkg-config 0.29.2 h1bed415_8
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - ncurses 6.3 h5eee18b_3
  run:
    - libgcc-ng >=11.2.0
    - ncurses >=6.3,<7.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libreadline.a
    - test -f ${PREFIX}/lib/libreadline${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libhistory.a
    - test -f ${PREFIX}/lib/libhistory${SHLIB_EXT}
    - python -c "import readline"
  requires:
    - python 3.*
about:
  description: 'The GNU Readline library provides a set of functions for use by applications

    that allow users to edit command lines as they are typed in.

    The Readline library includes additional functions to maintain a list of previously-entered
    command lines,

    to recall and perhaps reedit those lines, and perform csh-like history expansion
    on previous commands.

    '
  dev_url: https://git.savannah.gnu.org/cgit/readline.git/
  doc_url: https://tiswww.case.edu/php/chet/readline/rltop.html
  home: https://tiswww.case.edu/php/chet/readline/rltop.html
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  license_url: https://tiswww.case.edu/php/chet/readline/README
  summary: library for editing command lines as they are typed in
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: b56611bb-cba4-4aa5-bc99-24aa0cad6c3e
  recipe-maintainers:
    - asmeurer
    - croth1
    - jakirkham
    - jjhelmus
    - mingwandroid
    - msarahan
    - msarahan
    - ocefpaf
    - pelson
  remote_url: git@github.com:AnacondaRecipes/readline-feedstock.git
  sha: cb483f13dfde1e293829bd15f93ab99b86484950
