# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Jul 22 11:12:44 2023
# ------------------------------------------------

package:
  name: certifi
  version: 2023.7.22
source:
  - folder: certifi
    sha256: 539cc1d13202e33ca466e88b2807e29f4c13049d6d87031a3c110744495cb082
    url: https://pypi.io/packages/source/c/certifi/certifi-2023.7.22.tar.gz
  - folder: pip_wheel
    sha256: 0f35d63b7245205f4060efe1982f5ea2196aa6e5b26c07669adcf800e2542026
    url: https://pypi.io/packages/py2.py3/p/pip/pip-20.2.3-py2.py3-none-any.whl
  - folder: setuptools_wheel
    sha256: 4dd5bb0a0a0cff77b46ca5dd3a84857ee48c83e8223886b556613c724994073f
    url: https://pypi.io/packages/py3/s/setuptools/setuptools-49.6.0-py3-none-any.whl
build:
  noarch: python
  number: '0'
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2023.5.7 hbcca054_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.1.0 he5830b7_0
    - libgomp 13.1.0 he5830b7_0
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.42.0 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 hcb278e6_0
    - openssl 3.1.1 hd590300_1
    - python 3.11.4 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - tk 8.6.12 h27826a3_0
    - tzdata 2023c h71feb2d_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.7
test:
  imports:
    - certifi
about:
  description: 'Certifi is a curated collection of Root Certificates for validating
    the

    trustworthiness of SSL certificates while verifying the identity of TLS

    hosts.

    '
  dev_url: https://github.com/certifi/python-certifi
  doc_source_url: https://github.com/certifi/certifi.io/blob/master/README.rst
  doc_url: https://pypi.python.org/pypi/certifi
  home: http://certifi.io/
  license: ISC
  license_file: certifi/LICENSE
  summary: Python package for providing Mozilla's CA Bundle.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - pelson
    - sigmavirus24
