# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /feedstock/recipe, last modified Mon Mar 13 12:15:15 2023
# ------------------------------------------------

package:
  name: requests
  version: 2.28.1
source:
  sha256: 7c5599b102feddaa661c826c56ab4fee28bfd17f5abca1ebbe3e7f19d7c97983
  url: https://pypi.io/packages/source/r/requests/requests-2.28.1.tar.gz
build:
  number: '1'
  script: /croot/requests_1678709721434/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . -vv
  string: py310h06a4308_1
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2023.01.10 h06a4308_0
    - certifi 2022.12.7 py310h06a4308_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.2 h6a678d5_6
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 1.1.1t h7f8727e_0
    - pip 23.0.1 py310h06a4308_0
    - python 3.10.9 h7a1cb2a_2
    - readline 8.2 h5eee18b_0
    - setuptools 65.6.3 py310h06a4308_0
    - sqlite 3.40.1 h5082296_0
    - tk 8.6.12 h1ccaba5_0
    - tzdata 2022g h04d1e81_0
    - wheel 0.38.4 py310h06a4308_0
    - xz 5.2.10 h5eee18b_1
    - zlib 1.2.13 h5eee18b_0
  run:
    - certifi >=2017.4.17
    - charset-normalizer >=2,<3
    - idna >=2.5,<4
    - python >=3.10,<3.11.0a0
    - urllib3 >=1.21.1,<1.27
  run_constrained:
    - chardet >=3.0.2,<6
test:
  commands:
    - pip check
    - conda create -v --dry-run -n requests-test numpy
  imports:
    - requests
  requires:
    - conda
    - pip
about:
  description: 'Requests is the only Non-GMO HTTP library for Python, safe for human

    consumption.

    '
  dev_url: https://github.com/psf/requests
  doc_url: https://requests.readthedocs.io/en/latest/
  home: https://requests.readthedocs.io/en/latest/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "Requests is an elegant and simple HTTP library for Python, built with\
    \ \u2665."
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: be57ddec-837d-49c6-9073-c03df725a222
  recipe-maintainers:
    - carlodri
    - jakirkham
    - kalefranz
    - mcg1969
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - sigmavirus24
  remote_url: git@github.com:AnacondaRecipes/requests-feedstock.git
  sha: 1148d30a2caf12d6a7840635742eafbf093c9cef
