# This file created by conda-build 3.21.8
# ------------------------------------------------

package:
  name: libstdcxx-ng
  version: 11.2.0
source:
  path: /feedstock/recipe
build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  ignore_run_exports:
    - __glibc
  missing_dso_whitelist:
    - '*'
  number: 1
  string: h1234567_1
requirements:
  host:
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - sysroot_linux-64 2.17 h57e8cba_10
  run: []
test:
  commands:
    - test -f ${PREFIX}/lib/libstdc++.so
about:
  home: https://gcc.gnu.org/
  license: GPL-3.0-only WITH GCC-exception-3.1
  summary: The GNU C++ Runtime Library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 37674e30-5ce1-4880-93d5-86ce4d2dd03e
  recipe-maintainers:
    - katietz
  remote_url: git@github.com:AnacondaRecipes/gcc_toolchain-feedstock.git
  sha: 525581cbf9edd348209e0bf8c56be267e86ee969
