# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Aug 27 18:53:41 2019
# ------------------------------------------------

package:
    name: fonts-conda-forge
    version: '1'
build:
    noarch: generic
    number: '0'
    string: '0'
requirements:
    build:
        - font-ttf-dejavu-sans-mono 2.37 h6964260_0
        - font-ttf-inconsolata 2.001 hcb22688_0
        - font-ttf-source-code-pro 2.030 h7457263_0
        - font-ttf-ubuntu 0.83 h8b1ccd4_0
    run:
        - font-ttf-dejavu-sans-mono
        - font-ttf-inconsolata
        - font-ttf-source-code-pro
        - font-ttf-ubuntu
test:
    commands:
        - ls -alh ${PREFIX}/fonts/
        - du -sh ${PREFIX}/fonts/
about:
    description: 'A basic set of different fonts with at least one font covering as
        many

        scientific glyphs as possible, looking native on Ubuntu, being suitable

        for UI applications like Qt Creator and RStudio and being all in all

        reasonable sized. Install more fonts via conda (e.g. mscorefonts) or your

        system''s package manager for an increased font experience.

        '
    home: https://conda-forge.org/
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: The curated conda-forge standard fonts
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dbast
