# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /feedstock/recipe, last modified Tue Nov 22 14:16:26 2022
# ------------------------------------------------

package:
  name: libffi
  version: 3.4.2
source:
  patches:
    - 0004-LIBFFI_CLOSURE.patch
  sha256: 540fb721619a6aba3bdeef7d940d8e9e0e6d2c193595bc243241b77ff9e93620
  url: https://github.com/libffi/libffi/releases/download/v3.4.2/libffi-3.4.2.tar.gz
build:
  number: '6'
  run_exports:
    - libffi >=3.4,<4.0a0
  string: h6a678d5_6
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - autoconf 2.69 pl526hebd4dad_5
    - automake 1.16.5 pl5321h06a4308_0
    - binutils_impl_linux-64 2.38 h2a08ee3_1
    - binutils_linux-64 2.38.0 hc2dff05_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_0
    - gdbm 1.18 hd4cb3f1_4
    - gettext 0.21.0 hf68c758_0
    - gxx_impl_linux-64 11.2.0 h1234567_1
    - gxx_linux-64 11.2.0 hc2dff05_0
    - icu 58.2 he6710b0_3
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.38 h1181459_1
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-devel_linux-64 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libtool 2.4.6 h295c915_1008
    - libxml2 2.9.14 h74e7548_0
    - m4 1.4.18 h4e445db_0
    - make 4.2.1 h1bed415_1
    - ncurses 6.3 h5eee18b_3
    - patch 2.7.6 h7b6447c_1001
    - perl 5.34.0 h5eee18b_2
    - readline 8.2 h5eee18b_0
    - sed 4.8 h7b6447c_0
    - sysroot_linux-64 2.17 h57e8cba_10
    - texinfo 6.8 pl5262h7f8727e_0
    - xz 5.2.6 h5eee18b_0
    - zlib 1.2.13 h5eee18b_0
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
  run:
    - libgcc-ng >=11.2.0
    - libstdcxx-ng >=11.2.0
test:
  requires:
    - gcc_linux-64 11.2.0.*
    - gxx_linux-64 11.2.0.*
    - make
  source_files:
    - testsuite
    - testsuite/libffi.bhaible
about:
  description: 'The libffi library provides a portable, high level programming interface

    to various calling conventions. This allows a programmer to call any

    function specified by a call interface description at run-time.

    '
  dev_url: https://github.com/libffi/libffi
  doc_url: https://sourceware.org/libffi/
  home: https://sourceware.org/libffi/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Portable Foreign Function Interface Library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 07e3637d-e1dd-464c-9a5e-e917f102764f
  recipe-maintainers:
    - isuruf
    - scopatz
    - stefan-balke
  remote_url: git@github.com:AnacondaRecipes/libffi-feedstock.git
  sha: e80ea6afc58d63d6e31463210b424aded1cdeea2
