# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Jul 22 11:37:15 2023
# ------------------------------------------------

package:
  name: ca-certificates
  version: 2023.7.22
source:
  sha256: 539cc1d13202e33ca466e88b2807e29f4c13049d6d87031a3c110744495cb082
  url: https://pypi.io/packages/source/c/certifi/certifi-2023.7.22.tar.gz
build:
  number: '0'
  string: hbcca054_0
requirements:
  build: []
  run: []
test:
  commands:
    - test -f "${PREFIX}/ssl/cacert.pem"
    - test -f "${PREFIX}/ssl/cert.pem"
    - curl --cacert "${PREFIX}/ssl/cacert.pem" https://www.google.com
  requires:
    - curl
about:
  home: https://github.com/conda-forge/ca-certificates-feedstock
  license: ISC
  license_file: LICENSE
  summary: Certificates for use with other packages.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
