# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Aug 13 07:24:16 2019
# ------------------------------------------------

package:
    name: mscorefonts
    version: 0.0.1
source:
    sha256: 7d3c7abe6c6f21e1a48fa1cafccb1005dcfcff9ad2f135ae219854ace6be42d0
    url: https://github.com/pushcx/corefonts/archive/master.zip
build:
    noarch: generic
    number: '3'
    string: '3'
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - cabextract 1.9.1 h516909a_0
        - libgcc-ng 9.1.0 hdf63c60_0
test:
    commands:
        - test -f $PREFIX/fonts/andalemo.ttf
        - test -f $PREFIX/fonts/ariali.ttf
        - test -f $PREFIX/fonts/cour.ttf
        - test -f $PREFIX/fonts/georgia.ttf
        - test -f $PREFIX/fonts/impact.ttf
        - test -f $PREFIX/fonts/timesi.ttf
        - test -f $PREFIX/fonts/trebucit.ttf
        - test -f $PREFIX/fonts/verdanaz.ttf
        - test -f $PREFIX/fonts/arial.ttf
        - test -f $PREFIX/fonts/ariblk.ttf
        - test -f $PREFIX/fonts/courbd.ttf
        - test -f $PREFIX/fonts/georgiab.ttf
        - test -f $PREFIX/fonts/times.ttf
        - test -f $PREFIX/fonts/trebuc.ttf
        - test -f $PREFIX/fonts/verdana.ttf
        - test -f $PREFIX/fonts/webdings.ttf
        - test -f $PREFIX/fonts/arialbd.ttf
        - test -f $PREFIX/fonts/comic.ttf
        - test -f $PREFIX/fonts/courbi.ttf
        - test -f $PREFIX/fonts/georgiai.ttf
        - test -f $PREFIX/fonts/timesbd.ttf
        - test -f $PREFIX/fonts/trebucbd.ttf
        - test -f $PREFIX/fonts/verdanab.ttf
        - test -f $PREFIX/fonts/arialbi.ttf
        - test -f $PREFIX/fonts/comicbd.ttf
        - test -f $PREFIX/fonts/couri.ttf
        - test -f $PREFIX/fonts/georgiaz.ttf
        - test -f $PREFIX/fonts/timesbi.ttf
        - test -f $PREFIX/fonts/trebucbi.ttf
        - test -f $PREFIX/fonts/verdanai.ttf
about:
    description: 'In 1996 Microsoft started a font project named Core fonts

        for the Web. It was a freeware font project including fonts

        Andale Mono, Arial, Arial Black, Comic Sans MS, Courier New,

        Georgia, Impact, Times New Roman, Trebuchet MS, Verdana and

        Webdings.

        '
    dev_url: https://sourceforge.net/projects/mscorefonts/
    doc_url: https://sourceforge.net/projects/mscorefonts/
    home: https://sourceforge.net/projects/mscorefonts
    license: PROPRIETARY
    license_family: PROPRIETARY
    license_file: LICENSE
    summary: Microsofts Core fonts for the Web
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jan-janssen
