# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /feedstock/recipe, last modified Tue Feb 28 18:07:59 2023
# ------------------------------------------------

package:
  name: pyopenssl
  version: 23.0.0
source:
  sha256: c1cc5f86bcacefc84dada7d31175cae1b1518d5f60d3d0bb595a67822a868a6f
  url: https://pypi.io/packages/source/p/pyopenssl/pyOpenSSL-23.0.0.tar.gz
build:
  number: '0'
  script: /croot/pyopenssl_1677607685877/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
    -m pip install . -vv --no-deps
  string: py310h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2023.01.10 h06a4308_0
    - certifi 2022.12.7 py310h06a4308_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.2 h6a678d5_6
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 1.1.1t h7f8727e_0
    - pip 22.3.1 py310h06a4308_0
    - python 3.10.9 h7a1cb2a_0
    - readline 8.2 h5eee18b_0
    - setuptools 65.6.3 py310h06a4308_0
    - sqlite 3.40.1 h5082296_0
    - tk 8.6.12 h1ccaba5_0
    - tzdata 2022g h04d1e81_0
    - wheel 0.38.4 py310h06a4308_0
    - xz 5.2.10 h5eee18b_1
    - zlib 1.2.13 h5eee18b_0
  run:
    - cryptography >=38.0.0,<40
    - python >=3.10,<3.11.0a0
test:
  commands:
    - pip check
    - python -m OpenSSL.debug
  imports:
    - OpenSSL
    - OpenSSL.SSL
    - OpenSSL.crypto
    - OpenSSL.rand
  requires:
    - pip
about:
  description: 'pyOpenSSL is a high-level wrapper around a subset of the OpenSSL library.

    It includes:

    -SSL.Connection objects, wrapping the methods of Python''s portable sockets

    -Callbacks written in Python

    -Extensive error-handling mechanism, mirroring OpenSSL''s error codes

    and much more.

    '
  dev_url: https://github.com/pyca/pyopenssl
  doc_url: https://pyopenssl.readthedocs.org/en/stable/
  home: https://github.com/pyca/pyopenssl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python wrapper module around the OpenSSL library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 70ec8de0-942f-41db-9f92-a210af9866fe
  recipe-maintainers:
    - goanpeca
    - mingwandroid
    - nehaljwani
  remote_url: git@github.com:AnacondaRecipes/pyopenssl-feedstock.git
  sha: fe906feb6996223b1459309106ecc38c77b05d4b
