# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Aug 27 18:59:02 2019
# ------------------------------------------------

package:
    name: font-ttf-dejavu-sans-mono
    version: '2.37'
source:
    sha256: 5c6e497a2f36552cb5ffb112c413a6af39c0f3c47653662b90b4fa6499822fd7
    url: https://sourceforge.net/projects/dejavu/files/dejavu/2.37/dejavu-sans-ttf-2.37.zip
build:
    noarch: generic
    number: '0'
    string: hab24e00_0
test:
    commands:
        - test -f ${PREFIX}/fonts/DejaVuSans.ttf
    requires:
        - bzip2
about:
    description: 'DejaVu fonts are a font family based on the Vera Fonts. Its purpose
        is to provide a

        wider range of characters while maintaining the original look and feel through
        the

        process of collaborative development Monospace font for pretty code listings.

        Next to that, DejaVu contains a lot of mathematical and other symbols, arrows,
        braille

        patterns, etc

        '
    home: https://dejavu-fonts.github.io/
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Monospace font for pretty code listings with many mathematical and other
        symbols
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dbast
