# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Jul 28 14:00:28 2023
# ------------------------------------------------

package:
  name: conda
  version: 23.7.2
source:
  fn: conda-23.7.2.tar.gz
  sha256: 4fd44862ef87c73e4641b0c40a0873e103a097d6fd4a992041cfa9177ce20ac8
  url: https://github.com/conda/conda/archive/23.7.2.tar.gz
build:
  always_include_files:
    - bin/activate
    - bin/conda
    - bin/deactivate
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/conda_1690552914978/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . --no-deps --no-build-isolation -vv && /home/conda/feedstock_root/build_artifacts/conda_1690552914978/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m conda init --install
  string: py310hff52083_0
requirements:
  build: []
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - brotli-python 1.0.9 py310hd8f1fbe_9
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2023.7.22 hbcca054_0
    - certifi 2023.7.22 pyhd8ed1ab_0
    - cffi 1.15.1 py310h255011f_3
    - charset-normalizer 3.2.0 pyhd8ed1ab_0
    - colorama 0.4.6 pyhd8ed1ab_0
    - conda-package-handling 2.0.2 pyh38be061_0
    - conda-package-streaming 0.8.0 pyhd8ed1ab_0
    - editables 0.3 pyhd8ed1ab_0
    - hatch-vcs 0.3.0 pyhd8ed1ab_0
    - hatchling 1.18.0 pyhd8ed1ab_0
    - idna 3.4 pyhd8ed1ab_0
    - importlib-metadata 6.8.0 pyha770c72_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.1.0 he5830b7_0
    - libgomp 13.1.0 he5830b7_0
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.42.0 h2797004_0
    - libstdcxx-ng 13.1.0 hfd8a6a1_0
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 hcb278e6_0
    - openssl 3.1.1 hd590300_1
    - packaging 23.1 pyhd8ed1ab_0
    - pathspec 0.11.1 pyhd8ed1ab_0
    - pip 23.2.1 pyhd8ed1ab_0
    - pluggy 1.2.0 pyhd8ed1ab_0
    - pycparser 2.21 pyhd8ed1ab_0
    - pysocks 1.7.1 pyha2e5f31_6
    - python 3.10.12 hd12c33a_0_cpython
    - python_abi 3.10 3_cp310
    - readline 8.2 h8228510_1
    - requests 2.31.0 pyhd8ed1ab_0
    - ruamel.yaml 0.17.32 py310h2372a71_0
    - ruamel.yaml.clib 0.2.7 py310h1fa729e_1
    - setuptools 68.0.0 pyhd8ed1ab_0
    - setuptools-scm 7.1.0 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - tqdm 4.65.0 pyhd8ed1ab_1
    - trove-classifiers 2023.7.6 pyhd8ed1ab_0
    - typing-extensions 4.7.1 hd8ed1ab_0
    - typing_extensions 4.7.1 pyha770c72_0
    - tzdata 2023c h71feb2d_0
    - urllib3 2.0.4 pyhd8ed1ab_0
    - wheel 0.41.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
    - zipp 3.16.2 pyhd8ed1ab_0
    - zstandard 0.19.0 py310h1275a96_2
    - zstd 1.5.2 hfc55251_7
  run:
    - boltons >=23.0.0
    - conda-package-handling >=1.3.0
    - jsonpatch >=1.32
    - packaging >=23.0
    - pluggy >=1.0.0
    - pycosat >=0.6.3
    - pyopenssl >=16.2.0
    - python >=3.10,<3.11.0a0
    - python_abi 3.10.* *_cp310
    - requests >=2.27.0,<3
    - ruamel.yaml >=0.11.14,<0.18
    - setuptools >=60.0.0
    - toolz >=0.8.1
    - tqdm >=4
  run_constrained:
    - conda-build >=3
    - conda-content-trust >=0.1.1
    - conda-env >=2.6
    - conda-libmamba-solver >=22.12.0
    - cytoolz >=0.8.1
test:
  downstreams:
    - conda-smithy
  files:
    - commands_to_test.sh
    - test_runner.sh
  imports:
    - conda
    - conda_env
  requires:
    - mock
    - pexpect
    - responses
about:
  description: 'Conda is an open source package management system and environment

    management system for installing multiple versions of software packages

    and their dependencies and switching easily between them. It works on

    Linux, OS X and Windows, and was created for Python programs but can

    package and distribute any software.

    '
  dev_url: https://github.com/conda/conda
  doc_url: https://docs.conda.io/projects/conda/en/stable/
  home: https://conda.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: OS-agnostic, system-level binary package and environment manager.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - dbast
    - isuruf
    - jakirkham
    - jezdez
    - kenodegard
    - mbargull
    - ocefpaf
