# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /feedstock/recipe, last modified Thu Mar 23 08:57:36 2023
# ------------------------------------------------

package:
  name: tqdm
  version: 4.65.0
source:
  sha256: 1871fb68a86b8fb3b59ca4cdd3dcccbc7e6d613eeed31f4c332531977b89beb5
  url: https://pypi.io/packages/source/t/tqdm/tqdm-4.65.0.tar.gz
build:
  entry_points:
    - tqdm = tqdm.cli:main
  number: '0'
  script: /croot/tqdm_1679561862951/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . --no-deps -vv
  string: py310h2f386ee_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2023.01.10 h06a4308_0
    - certifi 2022.12.7 py310h06a4308_0
    - flit-core 3.8.0 py310h06a4308_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.2 h6a678d5_6
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 1.1.1t h7f8727e_0
    - packaging 23.0 py310h06a4308_0
    - pip 23.0.1 py310h06a4308_0
    - python 3.10.10 h7a1cb2a_2
    - readline 8.2 h5eee18b_0
    - setuptools 65.6.3 py310h06a4308_0
    - setuptools-scm 7.0.4 py310h06a4308_0
    - setuptools_scm 7.0.4 hd3eb1b0_0
    - sqlite 3.41.1 h5eee18b_0
    - tk 8.6.12 h1ccaba5_0
    - toml 0.10.2 pyhd3eb1b0_0
    - tomli 2.0.1 py310h06a4308_0
    - typing-extensions 4.4.0 py310h06a4308_0
    - typing_extensions 4.4.0 py310h06a4308_0
    - tzdata 2022g h04d1e81_0
    - wheel 0.38.4 py310h06a4308_0
    - xz 5.2.10 h5eee18b_1
    - zlib 1.2.13 h5eee18b_0
  run:
    - python >=3.10,<3.11.0a0
  run_constrained:
    - ipywidgets >=6
    - requests
    - slack-sdk
test:
  commands:
    - pip check
    - tqdm --help
    - tqdm -v | rg 4.65.0
    - pytest -k "not tests_perf"
  imports:
    - tqdm
  requires:
    - dask
    - keras
    - numpy
    - pip
    - pytest
    - pytest-asyncio
    - pytest-timeout
    - rich
    - ripgrep
  source_files:
    - pyproject.toml
    - setup.cfg
    - tests
about:
  dev_url: https://github.com/tqdm/tqdm
  doc_url: https://tqdm.github.io/
  home: https://tqdm.github.io/
  license: MPL-2.0 AND MIT
  license_family: MOZILLA
  license_file: LICENCE
  summary: A Fast, Extensible Progress Meter
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: e43bc087-8e6b-4420-8c45-832ab2fe99c3
  recipe-maintainers:
    - casperdcl
    - pmlandwehr
  remote_url: git@github.com:AnacondaRecipes/tqdm-feedstock.git
  sha: 3d3ee38916b11f0d4cf0ce967b3f6544784cd600
